services:
  neo4j-rag-base:
    container_name: neo4j-rag-base
    image: neo4j-rag-base-image
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - .:/home/root
    working_dir: /home/root
    user: root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  neo4j-rag:
    container_name: neo4j-rag
    image: neo4j:5.23.0
    ports:
      - 7888:7474
      - 7999:7687
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_memory_pagecache_size=2G # Page cache memory
      - NEO4J_dbms_memory_heap_initial__size=1G # Initial heap memory
      - NEO4J_dbms_memory_heap_max__size=3G # Maximum heap memory
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
      - ./db/import:/var/lib/neo4j/import